---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - backup.kop.hanshal.com
  resources:
  - podbackups
  - podrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.kop.hanshal.com
  resources:
  - podbackups/finalizers
  - podrestores/finalizers
  verbs:
  - update
- apiGroups:
  - backup.kop.hanshal.com
  resources:
  - podbackups/status
  - podrestores/status
  verbs:
  - get
  - patch
  - update
